name: Update profile contribution calendars

on:
  schedule:
    # Todos los días aproximadamente a las 06:15 de Ecuador.
    - cron: "15 11 * * *"

  # Permite ejecutarlo manualmente.
  workflow_dispatch:

  # Lo ejecuta cuando se modifica este workflow.
  push:
    branches:
      - main
    paths:
      - ".github/workflows/profile-metrics.yml"

permissions:
  contents: write

jobs:
  generate-calendars:
    name: Generate contribution calendars
    runs-on: ubuntu-latest

    steps:
      - name: Generate personal contribution calendar
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN_PERSONAL }}
          user: GuerreroWelinton

          filename: assets/metrics/personal-calendar.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update personal calendar [skip ci]"

          template: classic
          base: ""
          config_timezone: America/Guayaquil

          plugin_calendar: yes
          plugin_calendar_limit: 1

      - name: Generate professional contribution calendar
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN_WORK }}
          user: WguerreroZG

          filename: assets/metrics/work-calendar.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update professional calendar [skip ci]"

          template: classic
          base: ""
          config_timezone: America/Guayaquil

          plugin_calendar: yes
          plugin_calendar_limit: 1